version: '3.4'

services:
  myapp:
    image: myapp:1.0.0
    build:
      context: myapp
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - frontend
  myapi:
    image: myapi:1.0.0
    build:
      context: myapp
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
